name: X-Pro

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  # Change these values
  GitHubMail: "tollerdl.1234@gmail.com"
  GitHubName: "shakida" 
  Branch: "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup ENV
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.TOKEN }}@github.com" > ~/.git-credentials
      - name: Cleanup storage
      - uses: rokibhasansagar/slimhub_actions@main
      - name: Cloning..
        run: |
          git clone https://${GitHubName}:${{ secrets.TOKEN }}@github.com/${{ secrets.MIRROR_REPO }} -b ${Branch} source

      - name: Compile The Mirroring Docker Container
        run: |
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
          docker image ls

      - name: Running Docker
        timeout-minutes: 330 
        continue-on-error: true
        run: |
          docker run --privileged --rm -i mirror-bot

      - name: Looping
        continue-on-error: true
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop"
          git push -q https://${{ secrets.TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
